In [1]:
import pandas as pd

C:\Users\Admin\AppData\Local\Temp\ipykernel_7300\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df=pd.DataFrame({"Hours_studied":[1,2,3,4,5,6,7,8,9],"Test_score":[15,55,18,70,65,75,55,80,85]})
df

   Hours_studied  Test_score
0              1          15
1              2          55
2              3          18
3              4          70
4              5          65
5              6          75
6              7          55
7              8          80
8              9          85

In [3]:
df.describe()

       Hours_studied  Test_score
count       9.000000    9.000000
mean        5.000000   57.555556
std         2.738613   25.397397
min         1.000000   15.000000
25%         3.000000   55.000000
50%         5.000000   65.000000
75%         7.000000   75.000000
max         9.000000   85.000000

In [4]:
mean_hours=df["Hours_studied"].mean()
mean_hours

5.0

In [5]:
mean_score=df["Test_score"].mean()
mean_score

57.55555555555556

In [6]:
median_hours=df["Hours_studied"].median()
median_hours

5.0

In [7]:
median_score=df["Test_score"].median()
median_score

65.0

In [11]:
mode_hours=df["Hours_studied"].mode().iloc[2]
mode_hours

3

In [10]:
mode_score=df["Test_score"].mode().iloc[0]
mode_score

55

In [ ]:
is used to retrieve the first mode (most frequent value) for each column in a DataFrame.